// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"go.uber.org/zap"
	"telegram-api/internal/infrastructure_layer/hundlers"
	"telegram-api/internal/infrastructure_layer/repo"
	"telegram-api/internal/infrastructure_layer/router"
	"telegram-api/internal/infrastructure_layer/telegram"
)

// Injectors from wire.go:

func InitializeApplication(secret string, logger *zap.Logger) (telegram.TelegramBot, func(), error) {
	contextContext := context.Background()
	connection, cleanup := provideDBConnection(contextContext, logger)
	officeRepository := repo.NewOfficeRepository(connection)
	officeHundler := hundlers.NewOfficeHundler(officeRepository)
	routerRouter := router.NewRouter(officeHundler)
	telegramBot := telegram.NewTelegramBot(secret, routerRouter)
	return telegramBot, func() {
		cleanup()
	}, nil
}
