version: '3'

volumes:
  volt_volumes:

services:
  db:
    image: mysql:8.0
    volumes:
      - volt_volumes:/data/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - "3340:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root