version: '3'

volumes:
  volt_volumes:

services:
  inhotdesk:
    build: ./
    command: ./telegram-api
    restart: always
    ports:
      - "3012:3012"
    depends_on:
      - db
    environment:
      - USERNAME=root
      - PASSWORD=root
      - HOST=db
      - PORT=3306
      - DATABASE=volt
      - MAXOPENCONN=60
      - MAXIDLECONN=30
      - CONNLIFETIME=2
      - KEY=6257462459:AAGkfP_LpWilOGmB2z3CYwsKCfe9rtv7lJs
      - VERSION=1.0.7
      - ADMINS=km505603,irs_pro

  inhotdesk-cy:
    build: ./
    command: ./telegram-api
    restart: always
    ports:
      - "3014:3014"
    depends_on:
      - db
    environment:
      - USERNAME=root
      - PASSWORD=root
      - HOST=db
      - PORT=3306
      - DATABASE=volt_cy
      - MAXOPENCONN=60
      - MAXIDLECONN=30
      - CONNLIFETIME=2
      - KEY=6229893044:AAFg6cuCSfny8-jN6YJ3BR29_ApsmSouKs8
      - VERSION=1.0.7
      - ADMINS=dstepanovaa,natsem28

  inhotdesk-pf:
    build: ./
    command: ./telegram-api
    restart: always
    ports:
      - "3014:3014"
    depends_on:
      - db
    environment:
      - USERNAME=root
      - PASSWORD=root
      - HOST=db
      - PORT=3306
      - DATABASE=volt_pf
      - MAXOPENCONN=60
      - MAXIDLECONN=30
      - CONNLIFETIME=2
      - KEY=6258100352:AAEWtos2UTeWqTEcgLCYxmofvJOHDj_QJNM
      - VERSION=1.0.7
      - ADMINS=XeniaPo7

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  db:
    image: mysql:8.0
    volumes:
      - volt_volumes:/data/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"