version: '3'

volumes:
  volt_volumes:

services:
  inhotdesk:
    build: ./
    command: ./telegram-api
    restart: always
    ports:
      - "3012:3012"
    depends_on:
      - db
      - jaeger
    environment:
      - USERNAME=root
      - PASSWORD=root
      - HOST=db
      - PORT=3306
      - DATABASE=volt
      - MAXOPENCONN=60
      - MAXIDLECONN=30
      - CONNLIFETIME=2
      - KEY=5419202121:AAFotPHNAuL9B12NHziyFsWEhIDEfNGd3NU
      - VERSION=1.0.7
      - ADMINS=MayyaMalysheva,irs_pro
      - JAEGER_HOST=jaeger
      - JAEGER_PORT=14268

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  db:
    image: mysql:8.0
    volumes:
      - volt_volumes:/data/mysql
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volt
      MYSQL_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"